DIALECT = 'mysql'
DRIVER = 'pymysql'
host_name = '74f86e82@us-cdbr-iron-east-01.cleardb.net'
port = '3306'
database_name = 'heroku_ac29a93f14845dd'
user_name = 'bb2e2f8f43a936'
password = 'a4f21c13'
SQLALCHEMY_DATABASE_URI = '{}+{}://{}:{}@{}/{}'.format(DIALECT, DRIVER, user_name, password, host_name, database_name)
SQLALCHEMY_TRACK_MODIFICATIONS = False