DIALECT = 'mysql'
DRIVER = 'pymysql'
host_name = 'us-cdbr-iron-east-05.cleardb.net'
port = '3306'
database_name = 'heroku_135deb52640a216'
user_name = 'bf4c0cc20ecc57'
password = 'a4f21c13'
SQLALCHEMY_DATABASE_URI = '{}+{}://{}:{}@{}/{}'.format(DIALECT, DRIVER, user_name, password, host_name, database_name)
SQLALCHEMY_TRACK_MODIFICATIONS = False